### ISSUE TITLE
Caching doesn't support DynamoDBList types

### ISSUE THREAD

**Issue by howcheng** [scale-tone/linq2dynamodb#31]
Exception: 'Specified cast is not valid.' in AWSSDK.DynamoDBv2:
   at Amazon.DynamoDBv2.DocumentModel.DynamoDBEntry.AsString() in d:\Jenkins\jobs\v3-release-build\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\DynamoDBEntry.cs:line 582
   at Linq2DynamoDb.DataContext.EntityWrapper.GetDocumentIfDirty() in c:\Konst\projects\LINQ2DynamoDB-github\Sources\Linq2DynamoDb.DataContext\EntityWrapper.cs:line 60
   at Linq2DynamoDb.DataContext.TableDefinitionWrapper.SubmitChangesAsync() in c:\Konst\projects\LINQ2DynamoDB-github\Sources\Linq2DynamoDb.DataContext\TableDefinitionWrapper.cs:line 231
   at Linq2DynamoDb.DataContext.DataContext.<SubmitChanges>b__3(TableDefinitionWrapper t) in c:\Konst\projects\LINQ2DynamoDB-github\Sources\Linq2DynamoDb.DataContext\DataContext.cs:line 160
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Linq2DynamoDb.DataContext.DataContext.SubmitChanges() in c:\Konst\projects\LINQ2DynamoDB-github\Sources\Linq2DynamoDb.DataContext\DataContext.cs:line 160

The line in question is:
```
    if 
    (
        (!this._doc.ContainsKey(field.Key)) 
        && 
        (field.Value.AsString() == null)
    )
```

When `field.Value` is a DynamoDBList, you can't convert it to a string.

**Comment by scale-tone** [comment]
Fixed in version 2.0.0. Thanks.
