### ISSUE TITLE
Persisting an array value on a retrieved item sometimes fails

### ISSUE THREAD

**Issue by danieljurek** [scale-tone/linq2dynamodb#33]
Given a simple class: 
```
    public class TestObject {
        public string Id { get; set; }        
        public List<string> StringArray { get; set; }
    }
```
Some code that stores the class: 
```
            var entry = new TestObject {
                Id = "object-1"
                // note that StringArray = null in this case
            };
```

And some code that later retrieves, modifies, then tries to store the class: 
```
            var theItemWeStored = table.Where(item => item.Id == "object-1").Single();

            theItemWeStored.StringList = new List<string> { "entry-1", "entry-2" };
            dataContext.SubmitChanges();
```

You'll get an error: 
**Specified cast is not valid.**
```
   at Amazon.DynamoDBv2.DocumentModel.DynamoDBEntry.AsString() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\DynamoDBEntry.cs:line 582
   at Linq2DynamoDb.DataContext.EntityWrapper.GetDocumentIfDirty() in X:\opensource\linq2dynamodb\Sources\Linq2DynamoDb.DataContext\EntityWrapper.cs:line 60
   at Linq2DynamoDb.DataContext.TableDefinitionWrapper.SubmitChangesAsync() in X:\opensource\linq2dynamodb\Sources\Linq2DynamoDb.DataContext\TableDefinitionWrapper.cs:line 231
   at Linq2DynamoDb.DataContext.DataContext.<>c.<SubmitChanges>b__13_0(TableDefinitionWrapper t) in X:\opensource\linq2dynamodb\Sources\Linq2DynamoDb.DataContext\DataContext.cs:line 174
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Linq2DynamoDb.DataContext.DataContext.SubmitChanges() in X:\opensource\linq2dynamodb\Sources\Linq2DynamoDb.DataContext\DataContext.cs:line 174
   at repro_dynamodb_badness.Program.Main(String[] args) in X:\repro-dynamodb-badness\repro-dynamodb-badness\Program.cs:line 46
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Further tracing of the issue leads down to ~`EntityWrapper.cs:60` 

```
...
        public Document GetDocumentIfDirty()
        {
            this._newDoc = this._conversionFunctor(this.Entity);

            if (this._doc == null)
            {
                return this._newDoc;
            }

            bool isDirty = false;
            foreach (var field in this._newDoc)
            {
                // A field might be absent in old document and be set to null in new document.
                // This doesn't mean the value was changed.
                if 
                (
                    (!this._doc.ContainsKey(field.Key)) 
                    &&
                    (!(field.Value is DynamoDBList))    
                    &&
                    (field.Value.AsString() == null)   // <--- THE ERROR HAPPENS HERE
                )
                {
                    continue;
                }
...
```

In this case, `field.Key` is `StringList` (that is, the object property named "StringList") and `field.Value`  is of type `PrimitiveList`, not of type `DynamoDBList`. 

One fix might be to add a check for whether `field.Value is PrimitiveList`.

**Comment by scale-tone** [comment]
Hi Daniel, thanks for submitting this, but could you also specify the AWSSDK version you're using?

**Comment by danieljurek** [comment]
I reproduced the behavior using AWSSDK.DynamoDBv2 3.1.1.5.

**Comment by danieljurek** [comment]
Was having trouble with tests for the changes and then I saw that `Book` in the tests inherits from `EntityBase`. This seems to cause the `Book.RentingHistory` field to show up in `this._doc.ContainsKey(field.Key)` (from EntityWrapper.cs)... 

When I made `TestObject` inherit from EntityBase in my test harness the update did succeed. 

This bug behavior happens to POCOs, but it doesn't happen in classes which derive from `EntityBase`

**Comment by scale-tone** [comment]
Oh, yes, that must be a breaking change somewhere either inside AWSSDK or DynamoDB. As I can see, the crash occurs also if the TestObject.StringArray is initially set to an empty List<string>. Linq2DynamoDB correctly converts such an object (either with empty array field or with that field set to null) to a Document, but the field then doesn't appear in the table (checked via AWS web console) :( :(

Your fix really seems to help, thanks! But at the moment I'm not quite sure, that this changed behavior doesn't break something else. Will try to write more tests on that...

> This bug behavior happens to POCOs, but it doesn't happen in classes which derive from EntityBase

Yes, that was expected, as EntityWrapper is used only with EntityBase descendants.

**Comment by frankieleef** [comment]
This seems to be an issue still. However, instead of a StringSet I'm using a NumberSet. Whenever I try to update a NumberSet I get an error when I don't derive from EntityBase. When I do derive from EntityBase everything succeeds, but the document won't be updated in DynamoDB.

**Comment by scale-tone** [comment]
Hi Frank,

Are you using the source code or the NuGet package (which does not contain this fix yet)?

**Comment by frankieleef** [comment]
Aha, that should be it. I'm using the NuGet package. Do you have an estimation of when this gets updated?

**Comment by scale-tone** [comment]
Not a problem, will issue the new package tonight...

**Comment by frankieleef** [comment]
Thanks for the update! However, is it possible to store a NumberSet? Whenever I pass in a List of integers it gets converted to a StringSet.

**Comment by scale-tone** [comment]
As discussed [here](https://github.com/scale-tone/linq2dynamodb/issues/37), there's always an option to write your own simple IPropertyConverter for that. And please vote for that ticket, if you think, it's really important.
