### ISSUE TITLE
RedisCache update failures

### ISSUE THREAD

**Issue by megyfexid** [scale-tone/linq2dynamodb#46]
Currently the updates on all my classes are failing with:
Failed to update indexes. System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Amazon.DynamoDBv2.DocumentModel.ScanOperator'

It seems the serialisation is breaking in RedisTableCache.UpdateCacheAndIndexes.

Any advice?

**Comment by scale-tone** [comment]
Hello megyfexid,

I'm afraid, that info is not enough to be able to help you. Can you please provide the full details of the exception you're getting (especially the stack trace)? And also the code of your classes you're trying to update and the query you're making before doing the update?

Do I also understand correctly, that this was the exception you're seeing in your logs (the update of the cache failed), but the actual write to DynamoDB succeeds?

**Comment by megyfexid** [comment]
Thanks for looking at this.

Yes the write to dynamodb succeeds, this is what I am seeing in the logs:
Failed to update indexes. System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Amazon.DynamoDBv2.DocumentModel.ScanOperator'.
   at Linq2DynamoDb.DataContext.SearchCondition..ctor(SerializationInfo info, StreamingContext context)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Linq2DynamoDb.DataContext.Caching.Redis.GeneralUtils.ToObject[T](RedisValue value)
   at Linq2DynamoDb.DataContext.Caching.Redis.RedisTableCache.UpdateIndexes(RedisTransactionWrapper transaction, String hashKeyValue, IDictionary`2 addedEntities, IDictionary`2 modifiedEntities, ICollection`1 removedEntities)
   at Linq2DynamoDb.DataContext.Caching.Redis.RedisTableCache.UpdateCacheAndIndexes(IDictionary`2 addedEntities, IDictionary`2 modifiedEntities, ICollection`1 removedEntities)

My classes look like this:
   public class Question
    {
        public string ArticleId { get; set; }
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public int CorrectAnswerId { get; set; }
        //public DateTime EffDate { get; set; }
        //public DateTime EffTo { get; set; }
        public List<Answer> Answers { get; set; }
    }
    public class Answer
    {
        public int AnswerId { get; set; }
        public string AnswerText { get; set; }
    }

The code looks like this:
   public async Task questions(Guid articleId, [FromBody]ViewModels.Question question)
    {
      ArticlesDataContext ctx = new ArticlesDataContext();
      DataModels.Question saveQuestion = (await ctx.Questions.Where(_ => _.ArticleId == articleId.ToString() && _.QuestionId == question.id).ToListAsync()).SingleOrDefault();
      if (saveQuestion == null)
      {
        saveQuestion = new DataModels.Question
        {
          ArticleId = articleId.ToString()
        };
        ctx.Questions.InsertOnSubmit(saveQuestion);
      }
      saveQuestion.QuestionId = question.id;
      saveQuestion.QuestionText = question.question;
      saveQuestion.CorrectAnswerId = question.correctAnswerId;
      saveQuestion.Answers = question.answers.Select(a => new DataModels.Answer { AnswerId = a.id, AnswerText = a.answer }).ToList();
      await ctx.SubmitChangesAsync();
      //waiting for success before updating question count
      await UpdateQuestionCount(articleId, ctx);
    }

**Comment by scale-tone** [comment]
There's some "poisoning" index in your cache, that fails to be read (the WHERE clause of that index cannot be deserialized for some reason). 

The code you provided looks OK and doesn't give an answer to what that index might come from and why it might have such a weird SearchConditions value.

What I can propose now is to flush your cache (if you're able to dump all the values from it before flushing - that would be really useful for further investigation). This should resolve the immediate issue.

If after that you at some point notice the same error in your logs - come back with the full source code (if possible) and cache dump (if possible). We'll dive deeper then.

**Comment by megyfexid** [comment]
I found the issue. Linq2DynamoDb.DataContext.Caching.Redis only works with Newtonsoft.Json 9.0.1. Everything breaks with Newtonsoft.Json from 10.0.1.

The only problem now is Visual Studio won't let me downgrade to Newtonsoft.Json 9.0.1 because Microsoft.AspNetCore (>= 2.0.0) requires Newtonsoft.Json (>= 10.0.1).

How can I use Newtonsoft.Json 9.0.1 with Linq2DynamoDb.DataContext.Caching.Redis only and still use Newtonsoft.Json (>= 10.0.1) with Microsoft.AspNetCore?

Detected package downgrade: Newtonsoft.Json from 10.0.1 to 9.0.1. Reference the package directly from the project to select a different version. 
 webapi (>= 1.0.0) -> Microsoft.AspNetCore (>= 2.0.0) -> Microsoft.Extensions.Configuration.Json (>= 2.0.0) -> Newtonsoft.Json (>= 10.0.1) 
 webapi (>= 1.0.0) -> Newtonsoft.Json (>= 9.0.1)
Detected package downgrade: Newtonsoft.Json from 10.0.1 to 9.0.1. Reference the package directly from the project to select a different version. 
 webapi (>= 1.0.0) -> Microsoft.AspNetCore.Mvc (>= 2.0.0) -> Microsoft.AspNetCore.Mvc.Formatters.Json (>= 2.0.0) -> Microsoft.AspNetCore.JsonPatch (>= 2.0.0) -> Newtonsoft.Json (>= 10.0.1) 
 webapi (>= 1.0.0) -> Newtonsoft.Json (>= 9.0.1)
Detected package downgrade: Newtonsoft.Json from 10.0.1 to 9.0.1. Reference the package directly from the project to select a different version. 
 webapi (>= 1.0.0) -> Microsoft.AspNetCore.Mvc (>= 2.0.0) -> Microsoft.AspNetCore.Mvc.ViewFeatures (>= 2.0.0) -> Newtonsoft.Json.Bson (>= 1.0.1) -> Newtonsoft.Json (>= 10.0.1) 
 webapi (>= 1.0.0) -> Newtonsoft.Json (>= 9.0.1)

**Comment by megyfexid** [comment]
The only solution I have found is to downgrade to .net core 1.1. I tried putting the dynamodb stuff in it's own project but that still gave me the same issue. .Net core 2 seems to insist on using Newtonsoft.Json (>= 10.0.1).

Will you see if can maybe support .net core 2 in the future?

I think to do that you will have to make the RedisCache work with Newtonsoft.Json (>= 10.0.1).

**Comment by scale-tone** [comment]
Yes, supporting .net core 2 would be a good idea.

But when you say 'Everything breaks with Newtonsoft.Json from 10.0.1.' - can you please elaborate on this?
Is that just failure to deserialize Amazon.DynamoDBv2.DocumentModel.ScanOperator or anything else as well?

**Comment by scale-tone** [comment]
Fixed with https://www.nuget.org/packages/Linq2DynamoDb.DataContext.Caching.Redis/2.2.1.

**Comment by megyfexid** [comment]
Thank you very much. I can confirm this is fixed.

I updated to .net core 2.0 today and the Redis cache is now working.
