### ISSUE TITLE
Cannot have List<string> as property type

### ISSUE THREAD

**Issue by megyfexid** [scale-tone/linq2dynamodb#47]
If I try to use `List<string>` as a property type I get:
'System.InvalidCastException' in Linq2DynamoDb.DataContext.dll
Unable to cast object of type 'Amazon.DynamoDBv2.DocumentModel.DynamoDBList' to type 'Amazon.DynamoDBv2.DocumentModel.PrimitiveList'.
  at lambda_method(Closure , DynamoDBEntry )
   at Linq2DynamoDb.DataContext.Utils.DynamoDbConversionUtils.ToObject(Document doc, Type entityType)
   at Linq2DynamoDb.DataContext.ReaderBase`1.<.ctor>b__0_0(Document doc)
   at Linq2DynamoDb.DataContext.ReaderBase`1.SetCurrent(Document doc)
   at Linq2DynamoDb.DataContext.TableDefinitionWrapperBase.SingleDocReader`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at webapi.Controllers.ArticlesController.<Approver>d__2.MoveNext() in C:\Projects\angular4-seed\webapi\Controllers\ArticlesController.cs:line 62

My class looks like this:
```
public class Customer
  {
    public Guid CustomerId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    //couldn't use List<string> because linq2dynamodb has a bug
    public List<string> ApproverProfTypes { get; set; }
  }
```
The workaround at the moment is to wrap the string in another class:
```
public class Customer
  {
    public Guid CustomerId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    //couldn't use List<string> because linq2dynamodb has a bug
    public List<ProfTypes> ApproverProfTypes { get; set; }
  }

public class ProfTypes
{
public string ProfType { get; set; }
}
```

**Comment by megyfexid** [comment]
I get the error when calling this:
var approver = ctx.Customer.Where(c => c.CustomerId == ArticlesDataContext.loggedInCustomerId).ToList().First();

**Comment by scale-tone** [comment]
We even have a [test ](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext.Tests/QueryTests/BasicQueryTestsCommon.cs#L135) for List<string> fields, and it passes.

Can you elaborate on how you **created** that particular DynamoDB record you're trying to read? Was it created by Linq2DynamoDB or by some external code? Or manually maybe?
Can you please show the JSON of that record?
Can you please try to create that record with Linq2DynamoDB and try to read it?

**Comment by scale-tone** [comment]
No sound from the author, so closing this.
