### ISSUE TITLE
Cannot query nested objects

### ISSUE THREAD

**Issue by pvanroos** [scale-tone/linq2dynamodb#66]
I received this error when I tried to pass an expression that queried the property of a nested object:

System.NotSupportedException: The member '***' is not a member of *** table
   at Linq2DynamoDb.DataContext.ExpressionUtils.WhereVisitor.VisitMember(MemberExpression memberExp)
   at Linq2DynamoDb.DataContext.ExpressionUtils.WhereVisitor.VisitBinary(BinaryExpression binaryExp)
   at Linq2DynamoDb.DataContext.ExpressionUtils.WhereVisitor.VisitBinary(BinaryExpression binaryExp)
   at Linq2DynamoDb.DataContext.ExpressionUtils.QueryableMethodsVisitor.VisitWhereCall(Expression whereBodyExp)
   at Linq2DynamoDb.DataContext.ExpressionUtils.QueryableMethodsVisitor.VisitMethodCall(MethodCallExpression methodCallExp)
   at Linq2DynamoDb.DataContext.QueryProvider.PreEvaluateExpressionAndGetQueryableMethodsVisitor(Expression& expression)
   at Linq2DynamoDb.DataContext.QueryProvider.ExecuteQuery(Expression expression)
   at Linq2DynamoDb.DataContext.Query`1.GetEnumerator()

**Comment by scale-tone** [comment]
@pvanroos, querying on nested attributes is indeed not supported, but you can 
1) prepend your query with .ToList() ;
2) use a custom filter expression with .WithFilterExpression() method:
```
var describedMoviesQuery =
    from movie in moviesTable
    .WithFilterExpression(new Amazon.DynamoDBv2.DocumentModel.Expression
    {
        ExpressionStatement = "attribute_exists (Description)"
    })
    select movie;
```

**Comment by pvanroos** [comment]
Hello @scale-tone 

Thanks for the response.  I wrote a DynamoDb library that uses generics (i.e. TEntity) to handle CRUD operations.  So I allow the client of the lib to pass an Expression like 'Expression<Func<TEntity, bool>>' to the method and then I add it to the query like this:

     var items = cxt.GetTable<TEntity>()
                .Where(expression)
                .ToAsyncEnumerable();


On top of that, I return the IAsyncEnumerable response.  This works for queries on the root TEntity object until the client tries to pass an Expression that includes a query on an nested object or List in the root object.

Your solution is good but then I would have to translate the passed Expression value (Expression<Func<TEntity, bool>>) into a string. Correct?

**Comment by pvanroos** [comment]
@scale-tone 

I changed my query code to this:

var items = cxt.GetTable<TEntity>()
            .Where(expression.Compile())
            .ToAsyncEnumerable();

Note the '.Compile()'.  Now it works...  :-)
